---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	planner(planner)
	executor(executor)
	tool(tool)
	reflection(reflection)
	memory(memory)
	memory_update(memory_update)
	__end__([<p>__end__</p>]):::last
	__start__ --> memory;
	__start__ --> planner;
	executor -. &nbsp;end&nbsp; .-> __end__;
	executor -.-> tool;
	memory --> planner;
	planner --> executor;
	reflection -. &nbsp;end&nbsp; .-> __end__;
	reflection -.-> executor;
	reflection -.-> memory_update;
	tool --> reflection;
	memory_update --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
